import {AppProvider} from "@/components/AppContext";
import Header from "@/components/layout/Header";
import { Roboto } from 'next/font/google'
import './globals.css'
import {Toaster} from "react-hot-toast";

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="mt-12 p-8 text-center text-gray-200 bg-gradient-to-t from-[#373B44] to-[#4286f4]  ">
            <p className="text-sm text-white">© 2024 Все права защищены</p>
            <p className="text-xs mt-2 text-white">
              Разработано в <span className="font-semibold">ВЖ Телефон</span>
            </p>
          </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  )
}
